[package]
name = "baton"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
flexi_logger = "0.31.1"
futures-lite = "2.6.0"
log = "0.4.27"
nusb = "0.2.1"
ratatui = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
baton-studio = "0.1.0"
